name: Tag & Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for Docker image and Git'
        required: true
        type: string
      skip_latest:
        description: 'Skip pushing latest tag?'
        required: false
        type: boolean
        default: false

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout with push token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
    
      - name: Create and push git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . \
            -t ghcr.io/${{ github.repository }}:${{ inputs.tag }} \
            ${{ !inputs.skip_latest && format('-t ghcr.io/{0}:latest', github.repository) || '' }}

      - name: Push image with tag
        run: docker push ghcr.io/${{ github.repository }}:${{ inputs.tag }}

      - name: Push image as latest
        if: ${{ !inputs.skip_latest }}
        run: docker push ghcr.io/${{ github.repository }}:latest
